### ISSUE TITLE
Feature request: ignore dynamic imports

### ISSUE THREAD

**Issue by Sleaf** [threedayAAAAA/vite-plugin-circular-dependency#11]
Sometimes circular dependencies are expected (for example, when dynamically declaring a Component in a route, and the Component uses the router instance to fetch data). I hope these cases can be ignored.

**Comment by threedayAAAAA** [comment]
There are two ways to solve this problem
1. You can add exclude configurations to filter router configuration files
2.I would provide a switch to control dynamic imports since most of the time it won't cause runtime errors

**Comment by threedayAAAAA** [comment]
Upgrade to version [0.4.2](https://github.com/threedayAAAAA/vite-plugin-circular-dependency/tree/v0.4.2) or above. You can try using ignoreDynamicImport configuration
