### ISSUE TITLE
Please publish a new version

### ISSUE THREAD

**Issue by RedHatter** [threedayAAAAA/vite-plugin-circular-dependency#9]
Now that #8 is merged the plugin works in my project however I'm still unable to use it due to the fix not being released yet. If you could publish a new version to npm I would appreciate it.

**Comment by threedayAAAAA** [comment]
I'm very sorry, I forgot to deal with this matter some time ago due to some personal matters. I have now released the latest version. Thank you again for your support of this project. Your PR is crucial to this project.

https://www.npmjs.com/package/vite-plugin-circular-dependency/v/0.4.0
